- name: Adds a host to the DNS server
  hosts: all
  tasks:
    - name: Add the entry to local dns file
      lineinfile:
        path: {{ dns_zone_file }}
        line: "{{ vm_ip_address }} {{ vm_name }}{{ dns_domain }}"
    - name: Restart the DNS service
      systemd:
        name: {{ dns_service_name }}
        enabled: yes
        masked: no
        state: restarted