- name: Creates a new Virtual Machine
  hosts: all
  tasks:
    - name: Get current virtual machines
      virt:
        command: "list_vms"
      register: vms 
    - name: Print VMs
      debug:
        var: vms
    - name: Display all variables/facts known for a host
      debug:
      var: hostvars[inventory_hostname]