- name: New machine post install setup
  hosts: "{{ vm_name }}.el1.aa"
  gather_facts: no
  tasks:
    - name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
      wait_for:
        port: 22
        host: '{{ vm_ip_address }}'
        search_regex: OpenSSH
      delay: 5
      vars:
        ansible_connection: local
    - name: Ensure that the host is not already in known_hosts
      shell: "ssh-keygen -R {{ vm_name }}.el1.aa"
      changed_when: "vm_ip_address.rc != 0"
      delegate_to: localhost
    - name: Install EPEL
      yum:
        name: epel-release
        state: latest
    - name: Install necessary packages
      yum:
        name:
          - iptables
          - iptables-services
          - htop
          - vim
          - iftop
          - net-snmp
          - net-tools
          - yum-cron
          - yum-utils
          - wget
          - ntp
          - libselinux-python
        state: present
    - name: Remove unnecessary packages
      yum:
        name:
          - wpa_supplicant
          - polkit
          - chrony
          - firewalld
          - rsh-server
          - rsh
          - ypserv
          - tftp
          - tftp-server
          - talk
          - talk-server
          - telnet-server
          - xinetd
          - gcc*
          - authconfig
          - alsa-firmware
          - alsa-lib
          - alsa-tools-firmware
          - lsscsi
          - iprutils
          - ivtv-firmware
          - iw*-firmware
          - aic94xx-firmware
          - NetworkManager-libnm
          - NetworkManager
        state: absent
    - name: Enable SELinux
      selinux:
        policy: targeted
        state: enforcing
    - name: Configure yum max old kernels
      lineinfile: 
        dest: /etc/yum.conf
        regexp: '^(.*)installonly_limit(.*)$' 
        line: 'installonly_limit=2'
        backrefs: yes
    - name: Enable and start iptables
      systemd:
        name: iptables
        enabled: yes
        masked: no
    - name: Enable and start ip6tables
      systemd:
        name: ip6tables
        enabled: yes
        masked: no
    - name: Configure yum cron updates
      lineinfile: 
        dest: /etc/yum/yum-cron.conf
        regexp: '^(.*)apply_updates(.*)$' 
        line: 'apply_updates = yes'
        backrefs: yes
    - name: Enable yum cron
      systemd:
        name: yum-cron
        enabled: yes
        masked: no
    - name: Set the SSH daemon to ipv4 only
      lineinfile: 
        dest: /etc/ssh/sshd_config
        regexp: '^(.*)AddressFamily(.*)$' 
        line: 'AddressFamily inet'
        backrefs: yes
    - name: Set SSH to version 2 only
      lineinfile: 
        dest: /etc/ssh/sshd_config
        regexp: '^(.*)Protocol(.*)$' 
        line: 'Protocol 2'
        backrefs: yes
    - name: Update everything
      yum:
        name: '*'
        state: latest