- name: Stages the VM for pxe boot
  hosts: all
  gather_facts: no
  tasks:
    - name: Copy template file to mac address file
      copy:
        remote_src: yes
        src: /tftpboot/pxelinux.cfg/osinstalltemplate
        dest: /tftpboot/pxelinux.cfg/01-{{ vm_mac_address }}