- name: Wait for the VM to tftp the staged file
  hosts: all
  gather_facts: no
  tasks:
    - name: Wait for the file to be downloaded
      wait_for:
        path: /var/log/tftp.log
        search_regex: .+finished pxelinux.cfg/01-{{ vm_mac_address }}
      register: waitfor
    - name: Delete the staging file now no longer requried
      file:
        path: /tftpboot/pxelinux.cfg/01-{{ vm_mac_address }}
        state: absent
    - name: Wait for installation to finish
      wait_for:
        path: /var/log/osinstall.log
        search_regex: .+{{ vm_mac_address }} Installation has completed
        timeout: 600
    - name: Get the Virtual Machine IP address
      shell: 'grep {{ vm_mac_address }} /var/log/osinstall.log | awk ''{print $4}'''
      register: vm_ip_address
      changed_when: "vm_ip_address.rc != 0"
    - name: Add the new machine to AWX for later configuration
      uri:
        url: http://10.31.248.188/api/v2/hosts/
        method: POST
        user: awx
        password: your_pass
        body: "{\"name\": \"{{ vm_name }}.el1.aa\",\"description\": \"Added by VM Boot Playbook\",\"inventory\": 4,\"enabled\": true,\"instance_id\": \"\",\"variables\": \"\"}"
        force_basic_auth: yes
        status_code: 201
        body_format: json
      delegate_to: localhost
    - name: Store the IP Address for the next playbook
      set_stats:
        data:
          vm_ip_address:  "{{ (vm_ip_address.stdout) }}"