- name: Wait for the VM to tftp the staged file
  hosts: all
  tasks:
    - name: Wait for the file to be downloaded
      wait_for:
        path: /var/log/tftp.log
        search_regex: .+finished pxelinux.cfg/01-{{ vm_mac_address }}
      register: waitfor
    - name: Delete the staging file now no longer requried
      file:
        path: /tftpboot/pxelinux.cfg/01-{{ vm_mac_address }}
        state: absent
    - name: Wait for installation to finish
      wait_for:
        path: /var/log/osinstall.log
        search_regex: .+$( echo "{{ vm_mac_Address }}" | sed "s/-/:/g" ) Installation has completed
        timeout: 600
    - name: Get the Virtual Machine IP address
      shell: 'grep $( echo "{{ vm_mac_Address }}" | sed "s/-/:/g" ) /var/log/osinstall.log | awk ''{print $4}'''
      register: vm_ip_address
      changed_when: "vm_ip_address.rc != 0"
    - name: Store the IP Address for the next step
      set_stats:
        data:
          vm_mac_address:  "{{ (vm_ip_address.stdout) }}"