- name: Install the elastic RPM GPG key
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
- name: Copy the elastic yum repo
  copy:
    src: files/elastic.repo
    dest: /etc/yum.repos.d/elastic.repo
    owner: root
    group: root
    mode: '0600'
- name: Install necessary packages for ELK
  yum:
    name:
      - nginx
      - python-passlib
      - java-1.8.0-openjdk
      - elasticsearch
      - kibana
      - logstash
      - filebeat
    state: present
- name: Start and enable Nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
- name: Add https to input chain on iptables
  lineinfile:
    path: /etc/sysconfig/iptables
    regexp: '^-A INPUT -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT'
    insertafter: '^-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT'
    line: '-A INPUT -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT'
  register: iptables_http
- name: Add http to input chain on iptables
  lineinfile:
    path: /etc/sysconfig/iptables
    regexp: '^-A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT'
    insertafter: '^-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT'
    line: '-A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT'
  register: iptables_http
- name: Reload iptables with new rules
  systemd:
    name: iptables
    state: reloaded
  when: iptables_http.changed
- name: Set Elastic to listen on localhost
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '^#network.host'
    line: 'network.host: localhost'
- name: Start and enable elastic
  systemd:
    name: elasticsearch
    state: started
    enabled: yes
- name: Start and enable kibana
  systemd:
    name: kibana
    state: started
    enabled: yes
- name: Generate a password for nginx to elastic communications
  htpasswd:
    path: /etc/nginx/htpasswd.users
    name: admin
    password: 'password'
- name: Copy the elastic nginx configuration
  copy:
    src: files/elastic_nginx.conf
    dest: /etc/nginx/conf.d/elastic.el1.aa.conf
  register: nginx_configuration
- name: Restart nginx when the configuration has changed
  systemd: 
    name: nginx
    state: restarted
  when: nginx_configuration.changed
- name: Enable selinux for nginx
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes