- name: Install the elastic RPM GPG key
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
- name: Copy the elastic yum repo
  copy:
    src: files/elastic.repo
    dest: /etc/yum.repos.d/elastic.repo
    owner: root
    group: root
    mode: '0600'
- name: Install necessary packages for ELK
  yum:
    name:
      - nginx
      - git
      - java-1.8.0-openjdk
      - elasticsearch
      - kibana
      - logstash
      - filebeat
    state: present
- name: Restart start and enable Nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
- name: Add https to input chain on iptables
  lineinfile:
    path: /etc/sysconfig/iptables
    regexp: '^-A INPUT -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT'
    insertafter: '^-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT'
    line: '-A INPUT -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT'
  register: iptables_http
- name: Reload iptables with new rules
  systemd:
    name: iptables
    state: reloaded
  when: iptables_http.changed
