- name: Install necessary packages for shinobi
  yum:
    name:
      - curl
      - git
    state: present
- name: Add NodeJS repo
  shell: curl --silent --location https://rpm.nodesource.com/setup_8.x | bash -
- name: Install NodeJS
  yum:
    name:
      - nodejs
    state: present
- name: Git Clone shinobi
  git:
    repo: https://gitlab.com/Shinobi-Systems/Shinobi.git
    dest: /opt/shinobi